import './globals.css'
import { Poppins } from "next/font/google";
import Sidebar from "@/components/Layout/Sidebar";
import Header from '@/components/Layout/Header';

const poppin = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700", "900"],
  display: "swap",
});

export const metadata = {
  title: 'RD Saini Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
          integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
        <link rel="shortcut icon" href="/favicon.png" type="image/png" />
      </head>
      <body className={poppin.className}>
          <main>
            <Sidebar></Sidebar>
            <div className="main-content page-body">
              <Header></Header>
              <div >
                {children}
              </div>
            </div>
          </main>
      </body>
    </html>
  )
}